runtime: nodejs20
instance_class: F1

handlers:
  - url: /(.*\.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot))$
    static_files: dist/frontend/browser/\1
    upload: dist/frontend/browser/.*\.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot)$

  - url: /.*
    static_files: dist/frontend/browser/index.csr.html
    upload: dist/frontend/browser/index.csr.html